fashions/fashionlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('fashions.urls')),  # Keep
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]

# Serve the favicon
import os
from django.views.static import serve
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    path('KJfavicon.ico', serve, {
            'path': 'KJfavicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# References

# https://docs.djangoproject.com/en/2.2/ref/urls/#include

fashions/fashions/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'fashions'
urlpatterns = [
    path('', views.BrandView.as_view(), name = 'all'),
    path('fashions', views.BrandView.as_view(), name = 'fashions'),
    path('category', views.CategoryView.as_view(), name='category'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category_detail'),
    path('category/create',
        views.CategoryCreateView.as_view(success_url=reverse_lazy('fashions:all')), name='category_create'), 
    path('gender', views.GenderView.as_view(), name='gender'),
    path('gender/<int:pk>', views.GenderDetailView.as_view(), name='gender_detail'),
    path('gender/create',
        views.GenderCreateView.as_view(success_url=reverse_lazy('fashions:all')), name='gender_create'),       
    path('nation', views.NationView.as_view(), name='nation'),
    path('nation/<int:pk>', views.NationDetailView.as_view(), name='nation_detail'),
    path('nation/create',
        views.NationCreateView.as_view(success_url=reverse_lazy('fashions:all')), name='nation_create'),    
    path('brand', views.BrandView.as_view(), name='brand'),
    path('brand/<int:category_pk>/<int:gender_pk>/<int:nation_pk>', views.FilteredBrandView.as_view(), name='filteredbrand'),
    path('brand/<int:pk>', views.BrandDetailView.as_view(), name='brand_detail'),
    path('brand/create',
        views.BrandCreateView.as_view(success_url=reverse_lazy('fashions:brand')), name='brand_create'),
    path('brand/<int:pk>/update',
        views.BrandUpdateView.as_view(success_url=reverse_lazy('fashions:brand')), name='brand_update'),
    path('brand/<int:pk>/delete',
        views.BrandDeleteView.as_view(success_url=reverse_lazy('fashions:brand')), name='brand_delete'),
    path('brand_picture/<int:pk>', views.Brand_stream_file, name='brand_picture'),
    path('product', views.ProductView.as_view(), name='product'),
    path('product/<int:category_pk>/<int:gender_pk>/<int:season_pk>', views.FilteredProductView.as_view(), name='filteredproduct'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/create',
        views.ProductCreateView.as_view(success_url=reverse_lazy('fashions:product')), name='product_create'),
    path('product/<int:pk>/update',
        views.ProductUpdateView.as_view(success_url=reverse_lazy('fashions:product')), name='product_update'),
    path('product/<int:pk>/delete',
        views.ProductDeleteView.as_view(success_url=reverse_lazy('fashions:product')), name='product_delete'),
    path('product/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='product_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('product')), name='product_comment_delete'),
    path('product/<int:pk>/image',
        views.ImageCreateView.as_view(), name='product_image_create'),
    path('image/<int:pk>/delete',
        views.ImageDeleteView.as_view(success_url=reverse_lazy('product')), name='product_image_delete'),
    path('product_picture/<int:pk>', views.Image_stream_file, name='product_picture'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

fashions/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view() ),
    # Uncomment this below if you have setup base_bootstrap.html and configured social login
    # path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login)),
]

# The obtuse code below can be ignored - It dynamically switches
# between non-social login.html and social_login.html when we notice
# that social login has been configured in settings.py (later in the course)
# Or just uncomment the path above when you enable social login

from django.conf import settings
try:
    if len(settings.SOCIAL_AUTH_GITHUB_KEY) > 0 :
        social_login = 'registration/login_social.html'
        urlpatterns += [
            path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login)),
        ]
        print('Using',social_login,'as the login template for',settings.LOGIN_URL)
except:
    print('Using registration/login.html as the login template for',settings.LOGIN_URL)

fashions/fashions/views.py
from django.views import View
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse_lazy
from django.http import HttpResponse
from fashions.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from fashions.models import Gender, Nation, Season, Category, Brand, Product, CommentRating, ProductImage
from fashions.forms import BrandCreateForm, ProductCreateForm, NationCreateForm, CategoryCreateForm, GenderCreateForm,  ImageCreateForm
from fashions.forms import CommentForm
from django.urls import reverse
import pdb


###############################################
################ Nation #######################
###############################################

class NationView(LoginRequiredMixin, View):
    model = Nation
    template_name = "fashions/nation_list.html"

class NationDetailView(OwnerDetailView):
    model = Nation
    template_name = "fashions/nation_detail.html"
    def get(self, request, pk) :
        nation = Nation.objects.get(id=pk)
        brands = Brand.objects.filter(Nation=nation).order_by('-updated_at')
        context = {'brands' : brands}
        return render(request, self.template_name, context)

class NationCreateView(LoginRequiredMixin, View):
    template = "fashions/nation_form.html"
    success_url = reverse_lazy('fashions:all')
    def get(self, request, pk=None) :
        form = NationCreateForm()
        ctx = { 'form': form } 
        return render(request, self.template, ctx)

    def post(self, request, pk=None) :
        form = NationCreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        # Add owner to the model before saving
        nation = form.save(commit=False)
        nation.owner = self.request.user
        nation.save()
        return redirect(self.success_url)

###############################################
################ Gender #######################
###############################################

class GenderView(OwnerListView):
    model = Gender
    template_name = "fashions/gender_list.html"

class GenderDetailView(OwnerDetailView):
    model = Gender
    template_name = "fashions/gender_detail.html"
    def get(self, request, pk) :
        gender = Gender.objects.get(id=pk)
        brands = Brand.objects.filter(Gender=gender).order_by('-updated_at')
        context = {'brands' : brands}
        return render(request, self.template_name, context)

class GenderCreateView(LoginRequiredMixin, View):
    template = "fashions/gender_form.html"
    success_url = reverse_lazy('fashions:all')
    def get(self, request, pk=None) :
        form = GenderCreateForm()
        ctx = { 'form': form } 
        return render(request, self.template, ctx)

    def post(self, request, pk=None) :
        form = GenderCreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        # Add owner to the model before saving
        gender = form.save(commit=False)
        gender.owner = self.request.user
        gender.save()
        return redirect(self.success_url)

###############################################
################ Category #####################
###############################################

class CategoryView(OwnerListView):
    model = Brand
    template_name = "fashions/category_list.html"

class CategoryDetailView(OwnerDetailView):
    model = Category
    template_name = "fashions/category_detail.html"
    def get(self, request, pk) :
        category = Category.objects.get(id=pk)
        brands = Brand.objects.filter(Category=category).order_by('-updated_at')
        context = {'brands' : brands}
        return render(request, self.template_name, context)

class CategoryCreateView(LoginRequiredMixin, View):
    template = "fashions/category_form.html"
    success_url = reverse_lazy('fashions:all')
    def get(self, request, pk=None) :
        form = CategoryCreateForm()
        ctx = { 'form': form } 
        return render(request, self.template, ctx)

    def post(self, request, pk=None) :
        form = CategoryCreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        # Add owner to the model before saving
        category = form.save(commit=False)
        category.owner = self.request.user
        category.save()
        return redirect(self.success_url)

###############################################
################ Brand ########################
###############################################

class FilteredBrandView(OwnerListView):
    model = Brand
    template_name = "fashions/filtered_brand_list.html"
    def get(self, request, category_pk, gender_pk, nation_pk):
        if(category_pk != 0): 
            category = Category.objects.get(id=category_pk)
        if(gender_pk != 0): 
            gender = Gender.objects.get(id=gender_pk)
        if(nation_pk != 0): 
            nation = Nation.objects.get(id=nation_pk)
        if(gender_pk == 0 and nation_pk == 0):
            brands = Brand.objects.filter(categories__in=[category.id]).order_by('-updated_at')
        elif(category_pk == 0 and nation_pk == 0):
            brands = Brand.objects.filter(genders__in=[gender.id]).order_by('-updated_at')
        elif(category_pk == 0 and gender_pk == 0):
            brands = Brand.objects.filter(nation__id=nation.id).order_by('-updated_at')
        else:
            brands = Brand.objects.filter(categories=category, genders=gender, nation=nation).order_by('-updated_at')
        gender_list = Gender.objects.all()
        nation_list = Nation.objects.all()
        category_list = Category.objects.all()
        context = { 'brands' : brands, 'gender_list': gender_list, 'nation_list' : nation_list, 'category_list' : category_list}
        return render(request, self.template_name, context)

# class BrandView(LoginRequiredMixin, View):
#     model = Brand
#     template_name = "fashions/brand_list.html"
class BrandView(OwnerListView):
    model = Brand
    template_name = "fashions/brand_list.html"
    def get(self, request) :
        brands = Brand.objects.all()
        gender_list = Gender.objects.all()
        nation_list = Nation.objects.all()
        category_list = Category.objects.all()
        context = { 'brands' : brands, 'gender_list': gender_list, 'nation_list' : nation_list, 'category_list' : category_list}
        return render(request, self.template_name, context)

class BrandDetailView(OwnerDetailView):
    model = Brand
    template_name = "fashions/brand_detail.html"
    def get(self, request, pk) :
        brand = Brand.objects.get(id=pk)
        products = Product.objects.filter(brand=brand).order_by('-updated_at')
        gender_list = Gender.objects.all()
        nation_list = Nation.objects.all()
        category_list = Category.objects.all()
        brand_categories = brand.categories.all()
        brand_genders = brand.genders.all()
        context = { 'brand': brand, 'products': products, 'gender_list': gender_list, \
            'nation_list' : nation_list, 'category_list' : category_list, 'brand_categories': brand_categories, \
                'brand_genders' : brand_genders}
        return render(request, self.template_name, context)

class BrandCreateView(LoginRequiredMixin, View):
    template = "fashions/brand_form.html"
    success_url = reverse_lazy('fashions:brand')
    def get(self, request, pk=None) :
        form = BrandCreateForm()
        ctx = { 'form': form } 
        return render(request, self.template, ctx)

    def post(self, request, pk=None) :
        form = BrandCreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        # Add owner to the model before saving
        brand = form.save(commit=False)
        brand.owner = self.request.user
        brand.save()
        form.save_m2m()
        return redirect(self.success_url)

class BrandUpdateView(OwnerUpdateView):
    template = "fashions/brand_form.html"
    success_url = reverse_lazy('fashions:brand')
    def get(self, request, pk) :
        brand = get_object_or_404(Brand, id=pk, owner=self.request.user)
        form = BrandCreateForm(instance=brand)
        ctx = {'form': form }
        return render(request, self.template, ctx)

    def post(self, request, pk=None) :
        brand = get_object_or_404(Brand, id=pk, owner=self.request.user)
        form = BrandCreateForm(request.POST, request.FILES or None, instance=brand)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        brand = form.save(commit=False)
        brand.save()

        return redirect(self.success_url)

class BrandDeleteView(OwnerDeleteView):
    model = Brand
    template_name = "fashions/brand_delete.html"


def Brand_stream_file(request, pk) :
    brand = get_object_or_404(Brand, id=pk)
    response = HttpResponse()
    response['Content-Type'] = brand.content_type
    response['Content-Length'] = len(brand.picture)
    response.write(brand.picture)
    return response

###############################################
################ Product ######################
###############################################

class FilteredProductView(OwnerListView):
    model = Product
    template_name = "fashions/filtered_product_list.html"
    def get(self, request, category_pk, gender_pk, season_pk):

fashions/fashions/templates/fashions/base_menu.html
{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py -->
{% load staticfiles %}
{% block navbar %}
<!-- https://www.w3schools.com/booTsTrap/bootstrap_navbar.asp -->

<nav class="navbar navbar-default"></nav>
<header class="header_area">

        <div class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">
            <!-- Classy Menu -->
            <nav class="classy-navbar" id="essenceNav">
                <!-- Logo -->
                <a class="nav-brand" href="#"><img src="{% static 'KJlogo.png' %}" alt="" width="100" height="100"></a>
                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>
                <!-- Menu -->
                <div class="classy-menu">
                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>
                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul>
                            <li><a href="{% url 'fashions:brand' %}"><font size="+2"> 𝒮𝒽ℴ𝓅 </font></a>
    
                            </li>
                        </ul>
                    </div>
                    <!-- Nav End -->
                </div>
            </nav>
    
            <!-- Header Meta Data -->
            <div class="header-meta d-flex clearfix justify-content-end">
                <!-- Search Area -->
                <div class="favourite-area">
                    <a href="{% url 'fashions:brand' %}"><font size="-1"> ℬ𝓇𝒶𝓃𝒹 </font></a>
                </div>
                <!--  -->
                <!-- Favourite Area -->
                <div class="favourite-area">
                    <a href="{% url 'fashions:product' %}"><font size="-1"> 𝒫𝓇ℴ𝒹𝓊𝒸𝓉 </font></a>
                </div>
                <!-- User Login Info -->
                <div class="user-login-info">
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}?next={% url 'fashions:brand' %}"><font size="-1"> ℒℴℊℴ𝓊𝓉 </font></a>
                    {% else %}
                    <a href="{% url 'login' %}?next={% url 'fashions:brand' %}"><font size="-1"> ℒℴℊ𝒾𝓃 </font></a>                   
                    {% endif %}
                </div>
    
    
    
            </div>
    
        </div>
    </header>

    <!-- ##### Header Area End ##### -->
            <!-- ##### Breadcumb Area Start ##### -->
            <div class="breadcumb_area bg-img" style="background-image: url({% static 'img/title_br.jpg' %});">
                <div class="container h-100">
                    <div class="row h-100 align-items-center">
                        <div class="col-12">
                            <div class="page-title text-center">
                                <h2>Find your favorite!</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


{% endblock %}

fashions/fashions/templates/fashions/brand_list.html
{% extends "fashions/base_menu.html" %}

{% load app_tags %} <!-- see home/templatetags/app_tags.py -->
{% load staticfiles %}

{% block navbar %}
<!-- https://www.w3schools.com/booTsTrap/bootstrap_navbar.asp -->

<nav class="navbar navbar-default"></nav>
<header class="header_area">

    <div class="classy-nav-container breakpoint-off d-flex align-items-center justify-content-between">
        <!-- Classy Menu -->
        <nav class="classy-navbar" id="essenceNav">
            <!-- Logo -->
            <a class="nav-brand" href="#"><img src="{% static 'KJlogo.png' %}" alt="" width="100" height="100"></a>
            <!-- Navbar Toggler -->
            <div class="classy-navbar-toggler">
                <span class="navbarToggler"><span></span><span></span><span></span></span>
            </div>
            <!-- Menu -->
            <div class="classy-menu">
                <!-- close btn -->
                <div class="classycloseIcon">
                    <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                </div>
                <!-- Nav Start -->
                <div class="classynav">
                    <ul>
                        <li><a href="{% url 'fashions:brand' %}"><font size="+2"> 𝒮𝒽ℴ𝓅 </font></a>

                        </li>
                    </ul>
                </div>
                <!-- Nav End -->
            </div>
        </nav>

        <!-- Header Meta Data -->
        <div class="header-meta d-flex clearfix justify-content-end">
            <!-- Search Area -->
            <div class="favourite-area">
                <a href="{% url 'fashions:brand_create' %}"><font size="-1"> + ℬ𝓇𝒶𝓃𝒹 </font></a>
            </div>
            <!--  -->
            <!-- Favourite Area -->
            <div class="favourite-area">
                <a href="{% url 'fashions:product_create' %}"><font size="-1"> + 𝒫𝓇ℴ𝒹𝓊𝒸𝓉 </font></a>
            </div>
            <!-- User Login Info -->
            <div class="user-login-info">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}?next={% url 'fashions:all' %}"><font size="-1"> ℒℴℊℴ𝓊𝓉 </font></a>
                {% else %}
                <a href="{% url 'login' %}?next={% url 'fashions:all' %}"><font size="-1"> ℒℴℊ𝒾𝓃 </font></a>                   
                {% endif %}
            </div>



        </div>

    </div>
</header>

    <!-- ##### Header Area End ##### -->
            <!-- ##### Breadcumb Area Start ##### -->
            <div class="breadcumb_area bg-img" style="background-image: url({% static 'img/title_br.jpg' %});">
                <div class="container h-100">
                    <div class="row h-100 align-items-center">
                        <div class="col-12">
                            <div class="page-title text-center">
                                <h2>Find your favorite!</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



    <!-- ##### Shop Grid Area Start ##### -->
    <section class="shop_grid_area section-padding-80"><style> .widget{
            background-color: rgb(252, 250, 243);
          }</style>
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-4 col-lg-3">
                    <div class="shop_sidebar_area">

                        <!-- ##### Single Widget ##### -->
                        <div class="widget catagory mb-50">
                            <a><img src="{% static 'img/fashion.png' %}" alt="" width="150" height="150"></a>
                            <br>
                            <br>
                            <h6 class="widget-title mb-30"> Filter up your brands! </h6>

                            <!--  Catagories  -->
                            <div class="catagories-menu">
                                <ul id="menu-content2" class="menu-content collapse show">
                                    <!-- Single Item -->
                                    <li data-toggle="collapse" data-target="#gender">
                                            <a href="#"> <style> .sidetitle {
                                                    background-color: rgb(230, 230, 230);
                                                  }</style> <div class = "sidetitle"><font size="3"> Genders  </font><img src="{% static 'img/gender.png' %}" alt="" width="50" height="50">  
                                                  </div></a>
                                            <ul class="sub-menu collapse" id="gender">
                                                    <p>
                                                        {% for gender in gender_list %}
                                                                <li class = "sidelist">
                                                                <a href="{% url 'fashions:filteredbrand' 0 gender.id 0 %}"><B>{{ gender.name }}</B></a>
                                                                </li>
                                                                <br/>
                                                        {% endfor %}
                                                    </p>
                                                </ul>                                   
                                    <!-- Single Item -->
                                    <li data-toggle="collapse" data-target="#country">
                                            <a href="#"> <style> .sidetitle {
                                                    background-color: rgb(230, 230, 230);
                                                  }</style> <div class = "sidetitle"> <font size="3"> Countries  </font> <img src="{% static 'img/country.png' %}" alt="" width="25" height="25"> 
                                                  </div></a>
                                        <ul class="sub-menu collapse" id="country">
                                            <a href="{% url 'fashions:nation_create' %}"><font size="3" color="orange">Add a new country</font></a>
                                                    <p>
                                                    {% if nation_list %}
                                                    <ul>
                                                      {% for nation in nation_list %}
                                                        <li class = "sidelist">
                                                                <a href="{% url 'fashions:filteredbrand' 0 0 nation.id%}"><B>{{ nation.name }}</B></a>
                                                        </li>
                                                        <br/>
                                                      {% endfor %}
                                                    </ul>
                                                    {% else %}
                                                      <p>There are no nations currently.</p>
                                                    {% endif %}
                                                    </p>
                                        </ul>
                                    </li>
                                    <!-- Single Item -->
                                    <li data-toggle="collapse" data-target="#category">
                                            <a href="#"> <style> .sidetitle {
                                                    background-color: rgb(230, 230, 230);
                                                  }</style> <div class = "sidetitle"><font size="3"> Categories </font> <img src="{% static 'img/category.png' %}" alt="" width="30" height="30">
                                                  </div></a>
                                        <ul class="sub-menu collapse" id="category">
                                            <a href="{% url 'fashions:category_create' %}"><font size="3" color="red">Add a new category</font></a>
                                            <p>
                                                    {% if category_list %}
                                                    <ul>
                                                      {% for category in category_list %}
                                                        <li class = "sidelist">
                                                            <a href="{% url 'fashions:filteredbrand' category.id 0 0 %}"><B>{{ category.name }}</B></a>
                                                        </li>
                                                        <br/>
                                                      {% endfor %}
                                                    </ul>
                                                    {% else %}
                                                      <p>There are no categories currently.</p>
                                                    {% endif %}
                                                    </p>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-8 col-lg-9">
                    <div class="shop_grid_product_area">
                        <div class="row">
                            <div class="col-12">
                                <div class="product-topbar d-flex align-items-center justify-content-between">
                                    <!-- Total Products -->
                                    <div class="total-products">
                                            <p><a href="{% url 'fashions:product' %}">Switch to Product List</a><p>
                                    </div>
                                    <!-- Sorting -->
                                </div>
                            </div>
                        </div>
                        <div style="float:right">
                                <img src="{% static 'img/lady.jpg' %}" alt="" width="200" height="200">
                            </div>
                        
                        <div class="product-description"><img src="{% static 'img/brandtitle.jpg' %}" alt="" width="200" height="200"></div>
                        <br>
                            <p>
                            {% if brands %}
                            <ul>
                              {% for brand in brands %}
                                <li id="list4">
                                    <a href="{% url 'fashions:brand_detail'  brand.id %}"><font size="+2">{{ brand.name }}</font></a>
                                    {% if brand.owner == user %}
                                    (<a href="{% url 'fashions:brand_update' brand.id %}">Edit</a> |
                                    <a href="{% url 'fashions:brand_delete' brand.id %}">Delete</a>)
                                    </p>
                                    {% endif %}
                                </li>
                              {% endfor %}
                            </ul>
                            {% else %}
                              <p>There are no brands in your store.</p>
                            {% endif %}
                            </p>
                            <p>
                            <a href="{% url 'fashions:brand_create' %}"><font size="+1" color = "darkyellow"> Add a brand </font></a> |
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}?next={% url 'fashions:all' %}"><font size="+1"> Logout </font></a>
                            {% else %}
                            <a href="{% url 'login' %}?next={% url 'fashions:all' %}"><font size="+1"> Login </font></a>
                            {% endif %}
                            </p>
                            
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Shop Grid Area End ##### -->

{% endblock %}